# Generated by Django 2.0 on 2019-01-30 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=128)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('report', models.CharField(max_length=128)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=128)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=128)),
                ('startTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('C1', 'CHOICE1'), ('C2', 'CHOICE2'), ('C3', 'CHOICE3'), ('C4', 'CHOICE4')], default='C1', max_length=2)),
                ('numberOfTasks', models.IntegerField(default=1)),
                ('executorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_executor', to=settings.AUTH_USER_MODEL)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=128)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('exeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(max_length=128)),
                ('tType', models.CharField(choices=[('C1', 'CHOICE1'), ('C2', 'CHOICE2'), ('C3', 'CHOICE3'), ('C4', 'CHOICE4')], default='C1', max_length=2)),
                ('risk', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=128)),
                ('PRD', models.FileField(upload_to='uploads/')),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipTxt', models.CharField(max_length=128)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tasks')),
            ],
        ),
        migrations.AddField(
            model_name='taskinproject',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tasks'),
        ),
        migrations.AddField(
            model_name='projectinproduct',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projects'),
        ),
    ]
