# Generated by Django 2.0 on 2019-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190508_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='PRD',
            field=models.FileField(upload_to='uploads/', verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tType',
            field=models.CharField(choices=[('C1', 'Manual'), ('C2', 'Automatic not batchable'), ('C3', 'Automatic batchable')], default='C1', max_length=2, verbose_name='type'),
        ),
    ]
