# Generated by Django 2.0 on 2019-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190510_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodName',
            field=models.CharField(max_length=128, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='numberOfTasks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='startTime',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('C1', 'STARTED'), ('C2', 'SUSPENDED'), ('C3', 'FUTURE'), ('C4', 'ENDED')], default='C1', max_length=2),
        ),
    ]
