# Generated by Django 2.0 on 2018-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Editor'), ('W', 'Worker')], default='W', max_length=2),
        ),
    ]
