# Generated by Django 2.0 on 2018-11-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20181101_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group123',
            new_name='group',
        ),
    ]
