# Generated by Django 2.0 on 2018-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='generic', max_length=10, null=True),
        ),
    ]
