# Generated by Django 2.0 on 2018-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20181101_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default-user.png', upload_to='treasure_image'),
        ),
    ]
