# Generated by Django 2.0 on 2018-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20181105_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default-user.png', upload_to='user_image'),
        ),
    ]
