# Generated by Django 2.0 on 2018-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20181105_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_image/default-user.jpg', upload_to='user_image'),
        ),
    ]
