# Generated by Django 2.0 on 2019-01-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
